### ISSUE TITLE
Which Framework?

### ISSUE THREAD

**Issue by ChicagoGupta** [liveplant/liveplant.io#1]

**Comment by austinpray** [comment]
Gonna copypasta: http://about.liveplant.io/meetup/progress/2015/05/08/hello-world.html#liveplantio

If I had my pick: I recommend we implement this in ES6 with react and flux. ES6 transpilation and ES6 modules will happen through babel and browserify. As far as the decision to use flux: I am not totally sure about it. This type of project is what it was built for specifically but it’s definitely a bit strange for people who are used to traditional MVC. Another option is to use Ember as it might be easier for newer folks to work on. Angular is not a good fit for this project.

I **do not** want to use bower. I just have no desire to use two package managers and with browserify there is no reason to use bower. So that kind of kills ember-cli. However our setup can be very close to ember-cli and we just have browserify handle the fancy asset stuff.

So here are the options in my head:
- React + Flux
- React + Backbone
- Ember (browserify)
- ~~Ember (ember-cli)~~

Gonna gather my thoughts and make a proper pro/con list.

**Comment by austinpray** [comment]
React + whatevs
